server {
  listen 8081;
  server_name _;
  root /sites/training-dashboard-bog/dist;
  index index.html;
  location / {
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 8082;
  server_name _;
  root /sites/race-map-bog;
  index index.html;
  location / {
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 8083;
  server_name _;
  root /sites/cerco-casa;
  index index.html;

  location /api/notes {
    proxy_ssl_server_name on;
    proxy_set_header Host cerco-casa-bogdan-camilla.netlify.app;
    proxy_pass https://cerco-casa-bogdan-camilla.netlify.app/api/notes;
  }

  location = /grazie.html {
    proxy_ssl_server_name on;
    proxy_set_header Host cerco-casa-bogdan-camilla.netlify.app;
    proxy_pass https://cerco-casa-bogdan-camilla.netlify.app/grazie.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
